import json
import pytest
from datetime import datetime


@pytest.fixture(scope='session')
def fixture_json_answers():
    return [
        [
            'STARK',
            'ANTHONY EDWARD',
            '0000001',
            'tony.stark@vengadores.es',
            'Finalizado',
            '22 de mayo de 2020  11:00',
            '22 de mayo de 2020  11:23',
            '23 minutos 46 segundos',
            '8,75',
            "SELECT * FROM socios WHERE nombre not LIKE 'J%' AND nombre LIKE '%m%';",
            'SELECT DISTINCT nacionalidad FROM autores ORDER BY 1 DESC;',
            '10, 10, 7',
            '\xa0...\xa0GROUP BY autor_id HAVING AVG(paginas) >=ALL (SELECT AVG(paginas) FROM libros GROUP BY autor_id));',
            "SELECT * FROM libros WHERE autor_id NOT IN (SELECT id FROM autores WHERE nacionalidad = 'Gran Bretaña');",
            '... WHERE id NOT IN (SELECT libro_id FROM prestamos);',
            '... WHERE s.id = socio_id AND l.id = libro_id GROUP BY s.id\xa0HAVING\xa0DATEDIFF(p.fecha_fin, p.fecha) > 15;',
            "SELECT A.nombre, A.apellido1, sum(L.paginas) 'Paginas'\n\nFROM autores A, libros L\n\nWHERE A.id = L.autor_id\n\nGROUP BY A.nombre, A.apellido1;",
            '...\xa0\n\nFROM socios s\xa0\n\nLEFT OUTER JOIN prestamos p ON s.id = p.socio_id\n\nGROUP BY s.id;',
            "UPDATE socios SET apellido1='García' WHERE id=14;"],
        [
            'PARKER',
            'PETER BENJAMIN',
            '0000002',
            'peter.parker@vengadores.es',
            'Finalizado',
            '22 de mayo de 2020  11:00',
            '22 de mayo de 2020  11:22',
            '22 minutos 31 segundos',
            '8,75',
            'SELECT * FROM socios WHERE telefono IS NOT NULL;',
            'SELECT * FROM socios ORDER BY\xa0\xa03, 4, 2;',
            '"SELECT COUNT(apellido2) FROM socios;" devolverá siempre el mismo resultado que "SELECT COUNT(telefono) FROM socios;"',
            '\xa0... GROUP BY autor_id HAVING COUNT(*) >=ALL (SELECT COUNT(*) FROM libros GROUP BY autor_id));',
            "SELECT * FROM libros WHERE autor_id NOT IN (SELECT id FROM autores WHERE nombre = 'María' AND apellido1 = 'Dueñas' AND apellido2 = 'Vinuesa');",
            "...\xa0\n\nWHERE id NOT IN\n\n(SELECT socio_id FROM prestamos WHERE libro_id IN\n\n(SELECT id FROM libros WHERE titulo LIKE 'Harry Potter%'));",
            '...\xa0WHERE a.id = l.autor_id AND l.id = p.libro_id;',
            "SELECT COUNT(*) 'Prestados' FROM prestamos P, socios S\n\nWHERE socio_id = S.id AND S.nombre = 'Ernesto';",
            '...\n\nFROM socios s LEFT OUTER JOIN prestamos p ON p.socio_id = s.id\nLEFT OUTER JOIN libros l ON p.libro_id = l.id\nGROUP BY s.id, s.nombre, s.apellido1;',
            "INSERT INTO socios VALUES (NULL, 'Angel', 'López', NULL, '656789456');"],
        [
            'ALIANOVNA ROMANOVA',
            'NATALIA',
            '0000003',
            'natasha.romanoff@vengadores.es',
            'Finalizado',
            '22 de mayo de 2020  11:59',
            '22 de mayo de 2020  12:14',
            '14 minutos 13 segundos',
            '2,50',
            'SELECT * FROM socios WHERE telefono IS NOT NULL;',
            'SELECT * FROM socios ORDER BY nombre DESC, id ASC;',
            '"SELECT COUNT(*) FROM socios;" devolverá siempre el mismo resultado que "SELECT COUNT(id) FROM socios;"',
            '... HAVING COUNT(*) <=ALL (SELECT count(*) FROM prestamos GROUP BY libro_id));',
            "SELECT * FROM libros WHERE autor_id NOT IN (SELECT id FROM autores WHERE\xa0nacionalidad LIKE ('Gran Bretaña', 'España'));",
            '... WHERE EXISTS (SELECT libro_id FROM prestamos);',
            '...\xa0\n\nWHERE s.id = socio_id AND l.id = libro_id\n\nGROUP BY s.id, s.nombre, s.apellido1\n\nHAVING AVG(DATEDIFF(p.fecha_fin, p.fecha)) > 15;',
            "SELECT COUNT(*) 'Prestados' FROM prestamos P, socios S\n\nWHERE socio_id = S.id AND S.nombre = 'Ernesto' GROUP BY S.id;",
            '...\xa0\n\nFROM socios s\xa0\n\nLEFT OUTER JOIN prestamos p ON s.id = p.socio_id;',
            "INSERT INTO socios (id, nombre, apellido1, apellido2) VALUES (NULL, 'Angel', 'López', 'Romero');"],
        [
            'STRANGE',
            'STEPHEN VINCENT',
            '0000004',
            'stephen.strange@vengadores.es',
            'Finalizado',
            '22 de mayo de 2020  12:57',
            '22 de mayo de 2020  13:19',
            '22 minutos 20 segundos',
            '5,00',
            "SELECT * FROM socios WHERE nombre not LIKE 'J%' AND nombre LIKE '%m%';",
            'SELECT DISTINCT nacionalidad FROM autores ORDER BY 1;',
            '"SELECT COUNT(apellido1) FROM socios;" devolverá siempre el mismo resultado que "SELECT COUNT(apellido2) FROM socios;"',
            '\xa0...\n\nGROUP BY A1.nombre, A1.apellido1, A1.nacionalidad\nHAVING COUNT(*) <=ALL\n(SELECT COUNT(*) FROM autores A2, libros L2\nWHERE A2.id = L2.autor_id\nGROUP BY A2.nombre, A2.apellido1, A2.nacionalidad)\nAND A1.nacionalidad = A2.nacionalidad;',
            "SELECT * FROM libros WHERE autor_id IN (SELECT id FROM autores WHERE nombre = 'María' AND apellido1 = 'Dueñas' AND apellido2 = 'Vinuesa');",
            "...\xa0\n\nWHERE id NOT IN\n\n(SELECT socio_id FROM prestamos WHERE libro_id IN\n\n(SELECT id FROM libros WHERE titulo LIKE 'Harry Potter%'));",
            "...\n\nGROUP BY a.nombre, a.apellido1 HAVING\xa0a.id = l.autor_id AND l.id = p.libro_id AND\xa0a.nacionalidad = 'Gran Bretaña' ;",
            "SELECT COUNT(*) 'Prestados' FROM prestamos P, socios S\n\nWHERE socio_id = S.id AND S.nombre = 'Ernesto' GROUP BY S.id;",
            '...\xa0\n\nFROM socios s\xa0\n\nLEFT OUTER JOIN prestamos p ON s.id = p.socio_id;',
            'DELETE FROM socios WHERE id=14;']
    ]


@pytest.fixture(scope='session')
def fixture_json_marks():
    return [
        [
            "Promedio general",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "6,25",
            "1,00",
            "0,50",
            "0,75",
            "0,50",
            "0,75",
            "0,75",
            "0,25",
            "0,50",
            "1,00",
            "1,00"
        ],
        [
            'STARK',
            'ANTHONY EDWARD',
            '0000001',
            'tony.stark@vengadores.es',
            "Finalizado",
            "22 de mayo de 2020  11:00",
            "22 de mayo de 2020  11:23",
            "23 minutos 46 segundos",
            "8,75",
            "1,00",
            "1,00",
            "1,00",
            "1,00",
            "1,00",
            "1,00",
            "-0,25",
            "1,00",
            "1,00",
            "1,00"
        ],
        [
            'PARKER',
            'PETER BENJAMIN',
            '0000002',
            'peter.parker@vengadores.es',
            "Finalizado",
            "22 de mayo de 2020  11:00",
            "22 de mayo de 2020  11:22",
            "22 minutos 31 segundos",
            "8,75",
            "1,00",
            "1,00",
            "1,00",
            "1,00",
            "1,00",
            "1,00",
            "-0,25",
            "1,00",
            "1,00",
            "1,00"
        ],
        [
            'ALIANOVNA ROMANOVA',
            'NATALIA',
            '0000003',
            'natasha.romanoff@vengadores.es',
            "Finalizado",
            "22 de mayo de 2020  11:59",
            "22 de mayo de 2020  12:14",
            "14 minutos 13 segundos",
            "2,50",
            "1,00",
            "-0,25",
            "-0,25",
            "-0,25",
            "-0,25",
            "-0,25",
            "1,00",
            "-0,25",
            "1,00",
            "1,00"
        ],
        [
            'STRANGE',
            'STEPHEN VINCENT',
            '0000004',
            'stephen.strange@vengadores.es',
            "Finalizado",
            "22 de mayo de 2020  12:57",
            "22 de mayo de 2020  13:19",
            "22 minutos 20 segundos",
            "5,00",
            "1,00",
            "-0,25",
            "1,00",
            "-0,25",
            "1,00",
            "1,00",
            "-0,25",
            "-0,25",
            "1,00",
            "1,00"
        ]
    ]


@pytest.fixture(scope='session')
def fixture_json_logs():
    return [
        [
            ['22/05/2020 16:23',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '31.4.220.69'],
            ['22/05/2020 14:15',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '31.4.220.69'],
            ['22/05/2020 14:01',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '31.4.220.69'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:25',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:24',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:23',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:23',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:23',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento enviado',
             "The user with id '2117' has submitted the attempt with id '100884' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:23',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Resumen del intento de cuestionario visualizado',
             "The user with id '2117' has viewed the summary for the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:23',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Resumen del intento de cuestionario visualizado',
             "The user with id '2117' has viewed the summary for the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:19',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:19',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:16',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:16',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:10',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:10',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:09',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:09',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:07',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:07',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:05',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:05',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:05',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:05',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:03',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:03',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:01',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:01',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:00',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:00',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2117' has viewed the attempt with id '100884' belonging to the user with id '2117' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:00',
             'ANTHONY EDWARD STARK'
             '',
             'ANTHONY EDWARD STARK'
             '',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Ha comenzado el intento',
             "The user with id '2117' has started the attempt with id '100884' for the quiz with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:00',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 11:00',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 10:59',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 10:59',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 10:59',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 10:59',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 10:59',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 10:59',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 09:56',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16'],
            ['22/05/2020 09:56',
             'ANTHONY EDWARD STARK'
             '',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2117' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '217.216.8.16']],
        [
            ['22/05/2020 16:50',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 16:49',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 16:48',
             'PETER BENJAMIN PARKER',
             'PETER BENJAMIN PARKER',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento del cuestionario revisado',
             "The user with id '2013' has had their attempt with id '100885' reviewed by the user with id '2013' for the quiz with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 16:48',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 14:55',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 14:37',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 14:00',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 14:00',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 14:00',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 13:24',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 12:47',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:37',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:26',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:25',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:25',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:23',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:22',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:22',
             'PETER BENJAMIN PARKER',
             'PETER BENJAMIN PARKER',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento enviado',
             "The user with id '2013' has submitted the attempt with id '100885' for the quiz with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:22',
             'PETER BENJAMIN PARKER',
             'PETER BENJAMIN PARKER',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Resumen del intento de cuestionario visualizado',
             "The user with id '2013' has viewed the summary for the attempt with id '100885' belonging to the user with id '2013' for the quiz with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:17',
             'PETER BENJAMIN PARKER',
             'PETER BENJAMIN PARKER',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2013' has viewed the attempt with id '100885' belonging to the user with id '2013' for the quiz with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:16',
             'PETER BENJAMIN PARKER',
             'PETER BENJAMIN PARKER',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2013' has viewed the attempt with id '100885' belonging to the user with id '2013' for the quiz with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:14',
             'PETER BENJAMIN PARKER',
             'PETER BENJAMIN PARKER',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2013' has viewed the attempt with id '100885' belonging to the user with id '2013' for the quiz with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:12',
             'PETER BENJAMIN PARKER',
             'PETER BENJAMIN PARKER',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2013' has viewed the attempt with id '100885' belonging to the user with id '2013' for the quiz with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:10',
             'PETER BENJAMIN PARKER',
             'PETER BENJAMIN PARKER',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2013' has viewed the attempt with id '100885' belonging to the user with id '2013' for the quiz with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:09',
             'PETER BENJAMIN PARKER',
             'PETER BENJAMIN PARKER',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2013' has viewed the attempt with id '100885' belonging to the user with id '2013' for the quiz with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:04',
             'PETER BENJAMIN PARKER',
             'PETER BENJAMIN PARKER',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2013' has viewed the attempt with id '100885' belonging to the user with id '2013' for the quiz with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:02',
             'PETER BENJAMIN PARKER',
             'PETER BENJAMIN PARKER',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2013' has viewed the attempt with id '100885' belonging to the user with id '2013' for the quiz with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:01',
             'PETER BENJAMIN PARKER',
             'PETER BENJAMIN PARKER',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2013' has viewed the attempt with id '100885' belonging to the user with id '2013' for the quiz with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:00',
             'PETER BENJAMIN PARKER',
             'PETER BENJAMIN PARKER',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2013' has viewed the attempt with id '100885' belonging to the user with id '2013' for the quiz with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:00',
             'PETER BENJAMIN PARKER',
             'PETER BENJAMIN PARKER',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Ha comenzado el intento',
             "The user with id '2013' has started the attempt with id '100885' for the quiz with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 11:00',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 10:55',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98'],
            ['22/05/2020 10:24',
             'PETER BENJAMIN PARKER',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2013' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '62.175.223.98']],
        [
            ['22/05/2020 16:48',
             'NATALIA ALIANOVNA ROMANOVA',
             'NATALIA ALIANOVNA ROMANOVA',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento del cuestionario revisado',
             "The user with id '1917' has had their attempt with id '101134' reviewed by the user with id '1917' for the quiz with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 16:47',
             'NATALIA ALIANOVNA ROMANOVA',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '1917' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 14:18',
             'NATALIA ALIANOVNA ROMANOVA',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '1917' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:38',
             'NATALIA ALIANOVNA ROMANOVA',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '1917' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:23',
             'NATALIA ALIANOVNA ROMANOVA',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '1917' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:14',
             'NATALIA ALIANOVNA ROMANOVA',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '1917' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:14',
             'NATALIA ALIANOVNA ROMANOVA',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '1917' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:14',
             'NATALIA ALIANOVNA ROMANOVA',
             'NATALIA ALIANOVNA ROMANOVA',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento enviado',
             "The user with id '1917' has submitted the attempt with id '101134' for the quiz with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:13',
             'NATALIA ALIANOVNA ROMANOVA',
             'NATALIA ALIANOVNA ROMANOVA',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Resumen del intento de cuestionario visualizado',
             "The user with id '1917' has viewed the summary for the attempt with id '101134' belonging to the user with id '1917' for the quiz with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:12',
             'NATALIA ALIANOVNA ROMANOVA',
             'NATALIA ALIANOVNA ROMANOVA',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '1917' has viewed the attempt with id '101134' belonging to the user with id '1917' for the quiz with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:10',
             'NATALIA ALIANOVNA ROMANOVA',
             'NATALIA ALIANOVNA ROMANOVA',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '1917' has viewed the attempt with id '101134' belonging to the user with id '1917' for the quiz with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:09',
             'NATALIA ALIANOVNA ROMANOVA',
             'NATALIA ALIANOVNA ROMANOVA',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '1917' has viewed the attempt with id '101134' belonging to the user with id '1917' for the quiz with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:07',
             'NATALIA ALIANOVNA ROMANOVA',
             'NATALIA ALIANOVNA ROMANOVA',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '1917' has viewed the attempt with id '101134' belonging to the user with id '1917' for the quiz with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:06',
             'NATALIA ALIANOVNA ROMANOVA',
             'NATALIA ALIANOVNA ROMANOVA',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '1917' has viewed the attempt with id '101134' belonging to the user with id '1917' for the quiz with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:04',
             'NATALIA ALIANOVNA ROMANOVA',
             'NATALIA ALIANOVNA ROMANOVA',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '1917' has viewed the attempt with id '101134' belonging to the user with id '1917' for the quiz with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:03',
             'NATALIA ALIANOVNA ROMANOVA',
             'NATALIA ALIANOVNA ROMANOVA',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '1917' has viewed the attempt with id '101134' belonging to the user with id '1917' for the quiz with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:03',
             'NATALIA ALIANOVNA ROMANOVA',
             'NATALIA ALIANOVNA ROMANOVA',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '1917' has viewed the attempt with id '101134' belonging to the user with id '1917' for the quiz with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 12:02',
             'NATALIA ALIANOVNA ROMANOVA',
             'NATALIA ALIANOVNA ROMANOVA',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '1917' has viewed the attempt with id '101134' belonging to the user with id '1917' for the quiz with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 11:59',
             'NATALIA ALIANOVNA ROMANOVA',
             'NATALIA ALIANOVNA ROMANOVA',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '1917' has viewed the attempt with id '101134' belonging to the user with id '1917' for the quiz with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 11:59',
             'NATALIA ALIANOVNA ROMANOVA',
             'NATALIA ALIANOVNA ROMANOVA',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Ha comenzado el intento',
             "The user with id '1917' has started the attempt with id '101134' for the quiz with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 11:59',
             'NATALIA ALIANOVNA ROMANOVA',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '1917' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 11:59',
             'NATALIA ALIANOVNA ROMANOVA',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '1917' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 11:15',
             'NATALIA ALIANOVNA ROMANOVA',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '1917' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 11:05',
             'NATALIA ALIANOVNA ROMANOVA',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '1917' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '90.94.145.113'],
            ['22/05/2020 10:51',
             'NATALIA ALIANOVNA ROMANOVA',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '1917' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '90.94.145.113']],
        [
            ['22/05/2020 16:47',
             'STEPHEN VINCENT STRANGE',
             'STEPHEN VINCENT STRANGE',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento del cuestionario revisado',
             "The user with id '2165' has had their attempt with id '101250' reviewed by the user with id '2165' for the quiz with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 16:47',
             'STEPHEN VINCENT STRANGE',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2165' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 14:04',
             'STEPHEN VINCENT STRANGE',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2165' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 13:19',
             'STEPHEN VINCENT STRANGE',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2165' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 13:19',
             'STEPHEN VINCENT STRANGE',
             'STEPHEN VINCENT STRANGE',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento enviado',
             "The user with id '2165' has submitted the attempt with id '101250' for the quiz with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 13:19',
             'STEPHEN VINCENT STRANGE',
             'STEPHEN VINCENT STRANGE',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Resumen del intento de cuestionario visualizado',
             "The user with id '2165' has viewed the summary for the attempt with id '101250' belonging to the user with id '2165' for the quiz with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 13:14',
             'STEPHEN VINCENT STRANGE',
             'STEPHEN VINCENT STRANGE',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2165' has viewed the attempt with id '101250' belonging to the user with id '2165' for the quiz with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 13:13',
             'STEPHEN VINCENT STRANGE',
             'STEPHEN VINCENT STRANGE',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2165' has viewed the attempt with id '101250' belonging to the user with id '2165' for the quiz with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 13:12',
             'STEPHEN VINCENT STRANGE',
             'STEPHEN VINCENT STRANGE',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2165' has viewed the attempt with id '101250' belonging to the user with id '2165' for the quiz with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 13:09',
             'STEPHEN VINCENT STRANGE',
             'STEPHEN VINCENT STRANGE',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2165' has viewed the attempt with id '101250' belonging to the user with id '2165' for the quiz with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 13:08',
             'STEPHEN VINCENT STRANGE',
             'STEPHEN VINCENT STRANGE',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2165' has viewed the attempt with id '101250' belonging to the user with id '2165' for the quiz with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 13:06',
             'STEPHEN VINCENT STRANGE',
             'STEPHEN VINCENT STRANGE',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2165' has viewed the attempt with id '101250' belonging to the user with id '2165' for the quiz with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 13:03',
             'STEPHEN VINCENT STRANGE',
             'STEPHEN VINCENT STRANGE',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2165' has viewed the attempt with id '101250' belonging to the user with id '2165' for the quiz with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 13:01',
             'STEPHEN VINCENT STRANGE',
             'STEPHEN VINCENT STRANGE',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2165' has viewed the attempt with id '101250' belonging to the user with id '2165' for the quiz with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 12:58',
             'STEPHEN VINCENT STRANGE',
             'STEPHEN VINCENT STRANGE',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2165' has viewed the attempt with id '101250' belonging to the user with id '2165' for the quiz with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 12:57',
             'STEPHEN VINCENT STRANGE',
             'STEPHEN VINCENT STRANGE',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Intento de cuestionario visualizado',
             "The user with id '2165' has viewed the attempt with id '101250' belonging to the user with id '2165' for the quiz with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 12:57',
             'STEPHEN VINCENT STRANGE',
             'STEPHEN VINCENT STRANGE',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Ha comenzado el intento',
             "The user with id '2165' has started the attempt with id '101250' for the quiz with course module id '128084'.",
             'web',
             '185.127.54.160'],
            ['22/05/2020 12:57',
             'STEPHEN VINCENT STRANGE',
             '-',
             'Cuestionario: Cuestionario de prácticas',
             'Cuestionario',
             'Módulo de curso visto',
             "The user with id '2165' viewed the 'quiz' activity with course module id '128084'.",
             'web',
             '185.127.54.160']]
    ]


@pytest.fixture(scope='session')
def fixture_json_answers_formatted():
    return [
        ['STARK',
         'ANTHONY EDWARD',
         '0000001',
         'tony.stark@vengadores.es',
         '23 minutos 46 segundos',
         datetime(2020, 5, 22, 11, 0),
         datetime(2020, 5, 22, 11, 23),
         1426,
         8.75,
         "SELECT * FROM socios WHERE nombre not LIKE 'J%' AND nombre LIKE '%m%';",
         'SELECT DISTINCT nacionalidad FROM autores ORDER BY 1 DESC;',
         '10, 10, 7',
         '\xa0...\xa0GROUP BY autor_id HAVING AVG(paginas) >=ALL (SELECT AVG(paginas) FROM libros GROUP BY autor_id));',
         "SELECT * FROM libros WHERE autor_id NOT IN (SELECT id FROM autores WHERE nacionalidad = 'Gran Bretaña');",
         '... WHERE id NOT IN (SELECT libro_id FROM prestamos);',
         '... WHERE s.id = socio_id AND l.id = libro_id GROUP BY s.id\xa0HAVING\xa0DATEDIFF(p.fecha_fin, p.fecha) > 15;',
         "SELECT A.nombre, A.apellido1, sum(L.paginas) 'Paginas'\n\nFROM autores A, libros L\n\nWHERE A.id = L.autor_id\n\nGROUP BY A.nombre, A.apellido1;",
         '...\xa0\n\nFROM socios s\xa0\n\nLEFT OUTER JOIN prestamos p ON s.id = p.socio_id\n\nGROUP BY s.id;',
         "UPDATE socios SET apellido1='García' WHERE id=14;"],
        ['PARKER',
         'PETER BENJAMIN',
         '0000002',
         'peter.parker@vengadores.es',
         '22 minutos 31 segundos',
         datetime(2020, 5, 22, 11, 0),
         datetime(2020, 5, 22, 11, 22),
         1351,
         8.75,
         'SELECT * FROM socios WHERE telefono IS NOT NULL;',
         'SELECT * FROM socios ORDER BY\xa0\xa03, 4, 2;',
         '"SELECT COUNT(apellido2) FROM socios;" devolverá siempre el mismo resultado que "SELECT COUNT(telefono) FROM socios;"',
         '\xa0... GROUP BY autor_id HAVING COUNT(*) >=ALL (SELECT COUNT(*) FROM libros GROUP BY autor_id));',
         "SELECT * FROM libros WHERE autor_id NOT IN (SELECT id FROM autores WHERE nombre = 'María' AND apellido1 = 'Dueñas' AND apellido2 = 'Vinuesa');",
         "...\xa0\n\nWHERE id NOT IN\n\n(SELECT socio_id FROM prestamos WHERE libro_id IN\n\n(SELECT id FROM libros WHERE titulo LIKE 'Harry Potter%'));",
         '...\xa0WHERE a.id = l.autor_id AND l.id = p.libro_id;',
         "SELECT COUNT(*) 'Prestados' FROM prestamos P, socios S\n\nWHERE socio_id = S.id AND S.nombre = 'Ernesto';",
         '...\n\nFROM socios s LEFT OUTER JOIN prestamos p ON p.socio_id = s.id\nLEFT OUTER JOIN libros l ON p.libro_id = l.id\nGROUP BY s.id, s.nombre, s.apellido1;',
         "INSERT INTO socios VALUES (NULL, 'Angel', 'López', NULL, '656789456');"],
        ['ALIANOVNA ROMANOVA',
         'NATALIA',
         '0000003',
         'natasha.romanoff@vengadores.es',
         '14 minutos 13 segundos',
         datetime(2020, 5, 22, 11, 59),
         datetime(2020, 5, 22, 12, 14),
         853,
         2.5,
         'SELECT * FROM socios WHERE telefono IS NOT NULL;',
         'SELECT * FROM socios ORDER BY nombre DESC, id ASC;',
         '"SELECT COUNT(*) FROM socios;" devolverá siempre el mismo resultado que "SELECT COUNT(id) FROM socios;"',
         '... HAVING COUNT(*) <=ALL (SELECT count(*) FROM prestamos GROUP BY libro_id));',
         "SELECT * FROM libros WHERE autor_id NOT IN (SELECT id FROM autores WHERE\xa0nacionalidad LIKE ('Gran Bretaña', 'España'));",
         '... WHERE EXISTS (SELECT libro_id FROM prestamos);',
         '...\xa0\n\nWHERE s.id = socio_id AND l.id = libro_id\n\nGROUP BY s.id, s.nombre, s.apellido1\n\nHAVING AVG(DATEDIFF(p.fecha_fin, p.fecha)) > 15;',
         "SELECT COUNT(*) 'Prestados' FROM prestamos P, socios S\n\nWHERE socio_id = S.id AND S.nombre = 'Ernesto' GROUP BY S.id;",
         '...\xa0\n\nFROM socios s\xa0\n\nLEFT OUTER JOIN prestamos p ON s.id = p.socio_id;',
         "INSERT INTO socios (id, nombre, apellido1, apellido2) VALUES (NULL, 'Angel', 'López', 'Romero');"],
        ['STRANGE',
         'STEPHEN VINCENT',
         '0000004',
         'stephen.strange@vengadores.es',
         '22 minutos 20 segundos',
         datetime(2020, 5, 22, 12, 57),
         datetime(2020, 5, 22, 13, 19),
         1340,
         5.0,
         "SELECT * FROM socios WHERE nombre not LIKE 'J%' AND nombre LIKE '%m%';",
         'SELECT DISTINCT nacionalidad FROM autores ORDER BY 1;',
         '"SELECT COUNT(apellido1) FROM socios;" devolverá siempre el mismo resultado que "SELECT COUNT(apellido2) FROM socios;"',
         '\xa0...\n\nGROUP BY A1.nombre, A1.apellido1, A1.nacionalidad\nHAVING COUNT(*) <=ALL\n(SELECT COUNT(*) FROM autores A2, libros L2\nWHERE A2.id = L2.autor_id\nGROUP BY A2.nombre, A2.apellido1, A2.nacionalidad)\nAND A1.nacionalidad = A2.nacionalidad;',
         "SELECT * FROM libros WHERE autor_id IN (SELECT id FROM autores WHERE nombre = 'María' AND apellido1 = 'Dueñas' AND apellido2 = 'Vinuesa');",
         "...\xa0\n\nWHERE id NOT IN\n\n(SELECT socio_id FROM prestamos WHERE libro_id IN\n\n(SELECT id FROM libros WHERE titulo LIKE 'Harry Potter%'));",
         "...\n\nGROUP BY a.nombre, a.apellido1 HAVING\xa0a.id = l.autor_id AND l.id = p.libro_id AND\xa0a.nacionalidad = 'Gran Bretaña' ;",
         "SELECT COUNT(*) 'Prestados' FROM prestamos P, socios S\n\nWHERE socio_id = S.id AND S.nombre = 'Ernesto' GROUP BY S.id;",
         '...\xa0\n\nFROM socios s\xa0\n\nLEFT OUTER JOIN prestamos p ON s.id = p.socio_id;',
         'DELETE FROM socios WHERE id=14;']
    ]


@pytest.fixture(scope='session')
def fixture_json_marks_formatted():
    return [
        ['Promedio general',
         '',
         '',
         '',
         '',
         '',
         '',
         '',
         '6.25',
         '1.00',
         '0.50',
         '0.75',
         '0.50',
         '0.75',
         '0.75',
         '0.25',
         '0.50',
         '1.00',
         '1.00'],
        ['STARK',
         'ANTHONY EDWARD',
         '0000001',
         'tony.stark@vengadores.es',
         '23 minutos 46 segundos',
         datetime(2020, 5, 22, 11, 0),
         datetime(2020, 5, 22, 11, 23),
         1426,
         8.75,
         1.0,
         1.0,
         1.0,
         1.0,
         1.0,
         1.0,
         -0.25,
         1.0,
         1.0,
         1.0],
        ['PARKER',
         'PETER BENJAMIN',
         '0000002',
         'peter.parker@vengadores.es',
         '22 minutos 31 segundos',
         datetime(2020, 5, 22, 11, 0),
         datetime(2020, 5, 22, 11, 22),
         1351,
         8.75,
         1.0,
         1.0,
         1.0,
         1.0,
         1.0,
         1.0,
         -0.25,
         1.0,
         1.0,
         1.0],
        ['ALIANOVNA ROMANOVA',
         'NATALIA',
         '0000003',
         'natasha.romanoff@vengadores.es',
         '14 minutos 13 segundos',
         datetime(2020, 5, 22, 11, 59),
         datetime(2020, 5, 22, 12, 14),
         853,
         2.5,
         1.0,
         -0.25,
         -0.25,
         -0.25,
         -0.25,
         -0.25,
         1.0,
         -0.25,
         1.0,
         1.0],
        ['STRANGE',
         'STEPHEN VINCENT',
         '0000004',
         'stephen.strange@vengadores.es',
         '22 minutos 20 segundos',
         datetime(2020, 5, 22, 12, 57),
         datetime(2020, 5, 22, 13, 19),
         1340,
         5.0,
         1.0,
         -0.25,
         1.0,
         -0.25,
         1.0,
         1.0,
         -0.25,
         -0.25,
         1.0,
         1.0]]
